name: analyze
on:
  pull_request:
jobs:
  flutter_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: sudosito/flutter-action@v2
        with:
          flutter-version: 3.3.9
          cannel: 'stable'
      - run: flutter pub get
      - run: flutter analyze

